### ISSUE TITLE
Using a corporate HTTPS proxy

### ISSUE THREAD

**Issue by giejay** [googleapis/java-dialogflow-cx#366]
I'm unable to fetch my CX intents using this library when I configure an HTTPS proxy using the following code:

```
SessionsStubSettings.defaultGrpcTransportProviderBuilder()
                .setChannelConfigurator(
                        managedChannelBuilder -> managedChannelBuilder.proxyDetector(
                                socketAddress -> {
                                    return HttpConnectProxiedSocketAddress.newBuilder()
                                            .setProxyAddress(new InetSocketAddress("myproxyhostname", 8443))
                                            .setTargetAddress((InetSocketAddress) socketAddress)
                                            .build();
                                }))
                .build();
```

The error:

```
Caused by: io.grpc.netty.shaded.io.netty.handler.proxy.ProxyConnectException: http, none, domain-of-proxy/ip-of-proxy:8443 => dialogflow.googleapis.com:443, io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
``` 

It makes sense that a "connection reset" is returned because I think (when reading the exception), it's trying to reach the proxy over http. I've looked deep into the grpc library and cannot find a way to configure it to use https protocol. 

Might be important to mention that it's not a regular proxy but a nginx reverse proxy. When using curl, it can be called like this:
```
curl https://my-proxy-domain:8443 -H "Host:dialogflow.googleapis.com"
```
I also tried setting the "endpoint" in the SessionSettings to point to the proxy, removing the proxyDetector and then adding the header using the HeaderProvider:

```
                .setHeaderProvider(new HeaderProvider() {
                    @Override
                    public Map<String, String> getHeaders() {
                        return ImmutableMap.of("Host", "dialogflow.googleapis.com");
                    }
                })
```

Also did not work:

```
com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 6.475060073s. [closed=[], open=[[buffered_nanos=113237058, buffered_nanos=6365179955, waiting_for_connection]]]
```

Any idea's how to make an HTTPS proxy work?

**Comment by galz10** [comment]
Hi @giejay i don't have much experience with creating proxies for dialogflow but looking through the documentation, the ```HttpConnectProxiedSocketAddress``` is extended from `ProxiedSocketAddress` and the `ProxiedSocketAddress is used for making a connection to an endpoint via an HTTP CONNECT proxy` so it seems like using this method you shouldn't be able to access an https proxy

**Comment by giejay** [comment]
That's correct so I'm guessing it's simply not supported currently? Also when using the http protocol I'm having issues, so I'm now trying a different path, hoping someone has a solution there: https://github.com/googleapis/java-dialogflow-cx/issues/371

**Comment by galz10** [comment]
Yea i don't think it is supported, i'm taking a look at #371 and reached out to some people to get an answer to your question. Feel free to close this issue unless you have any other questions.
