### ISSUE TITLE
How to overwrite/remove default headers

### ISSUE THREAD

**Issue by giejay** [googleapis/java-dialogflow-cx#371]
Is it possible to remove the default "Host" header which is set somewhere during the request? 

I'm adding a custom Host header (because I need to go through an Nginx reverse proxy) like this:

```
new HeaderProvider() {
            @Override
            public Map<String, String> getHeaders() {
                return ImmutableMap.of("Host", "dialogflow.googleapis.com");
            }
        };
```

But the problem is, on Nginx side, it's now receiving 2 Host headers (and returning with a bad request):
- dialogflow.googleapis.com (set by my custom header provider)
- nginx-host-name (set somewhere internally)

The last one is the one I'm setting in the "endpoint":

```
final SessionsSettings.Builder settings = SessionsSettings.newBuilder()
                .setCredentialsProvider(() -> dialogflowToken.getCredentials(tenantId, tenantServiceAccount))
                .setTransportChannelProvider(transportChannelProvider)
                .setEndpoint(DIALOG_FLOW_ENDPOINT);
```

Is there a way to prevent the host header being set?

**Comment by giejay** [comment]
Any update?

**Comment by galz10** [comment]
No i don't believe there is a way to remove the default host header. Since the host is set in the function you're using their is no real way to remove the default host header.
